export { default as TipTapEditor } from './TipTapEditor'
export type { TipTapEditorHandle } from './TipTapEditor'
export { TipTapEditorWrapper, tiptapEditorWrapper } from './TipTapEditorWrapper'
export { configureMention } from './extensions/configureMention'
export type { MentionUser } from './extensions/configureMention'